In [1]:
import pandas as pd
import numpy as np

### This is an algorithm. not a model. No equation is given here.

K-nearest neighbour used to identify similar instances to your own example so you can get a better estimate

In [2]:
file = pd.read_csv("dc_airbnb.csv")
file

,host_response_rate,host_acceptance_rate,host_listings_count,accommodates,room_type,bedrooms,bathrooms,beds,price,cleaning_fee,security_deposit,minimum_nights,maximum_nights,number_of_reviews,latitude,longitude,city,zipcode,state
0,92%,91%,26,4,Entire home/apt,1.0,1.0,2.0,$160.00,$115.00,$100.00,1,1125,0,38.890046,-77.002808,Washington,20003,DC
1,90%,100%,1,6,Entire home/apt,3.0,3.0,3.0,$350.00,$100.00,NaN,2,30,65,38.880413,-76.990485,Washington,20003,DC
2,90%,100%,2,1,Private room,1.0,2.0,1.0,$50.00,NaN,NaN,2,1125,1,38.955291,-76.986006,Hyattsville,20782,MD
3,100%,NaN,1,2,Private room,1.0,1.0,1.0,$95.00,NaN,NaN,1,1125,0,38.872134,-77.019639,Washington,20024,DC
4,92%,67%,1,4,Entire home/apt,1.0,1.0,1.0,$50.00,$15.00,$450.00,7,1125,0,38.996382,-77.041541,Silver Spring,20910,MD
5,100%,100%,1,4,Entire home/apt,2.0,1.0,4.0,$99.00,NaN,NaN,1,1125,0,38.862486,-77.015062,Washington,20024,DC
6,100%,NaN,1,4,Entire home/apt,2.0,2.0,2.0,$100.00,$50.00,$150.00,3,1125,0,38.974738,-77.027076,Washington,20012,DC
7,100%,NaN,1,2,Entire home/apt,1.0,1.0,1.0,$100.00,NaN,NaN,1,1125,0,38.941486,-76.968485,Mount Rainier,20712,MD
8,94%,99%,8,2,Private room,1.0,1.5,1.0,$38.00,NaN,NaN,2,180,1,38.880105,-76.919031,Capitol Heights,20743,MD
9,100%,100%,9,2,Private room,1.0,NaN,1.0,$71.00,$10.00,NaN,2,365,4,38.975592,-77.010713,Takoma Park,20912,MD
10,100%,100%,1,4,Entire home/apt,2.0,1.5,2.0,$97.00,$50.00,$250.00,4,1125,5,38.980067,-77.015538,Takoma Park,20912,MD
11,88%,100%,1,1,Entire home/apt,1.0,1.0,1.0,$55.00,NaN,$100.00,3,1125,1,38.995938,-77.036141,Silver Spring,20910,MD
12,NaN,NaN,1,2,Private room,1.0,1.0,1.0,$50.00,$20.00,$150.00,2,14,0,38.992050,-77.046524,Silver Spring,20910,MD
13,68%,73%,7,2,Entire home/apt,0.0,1.0,1.0,$99.00,$125.00,NaN,7,1125,0,38.990226,-77.029817,Silver Spring,20910,MD
14,100%,100%,9,2,Private room,1.0,NaN,1.0,$60.00,$10.00,NaN,2,1125,2,38.975536,-77.008962,Takoma Park,20912,MD
15,100%,83%,1,2,Private room,1.0,1.0,1.0,$52.00,NaN,NaN,1,1125,1,38.940709,-76.965705,Mount Rainier,20712,MD
16,100%,100%,1,1,Private room,1.0,1.0,1.0,$23.00,$5.00,NaN,1,1125,1,38.961838,-76.993933,Hyattsville,20782,MD
17,NaN,100%,1,2,Shared room,1.0,1.0,2.0,$200.00,NaN,$100.00,1,1125,0,38.992030,-77.030906,Silver Spring,20910,MD
18,83%,80%,1,4,Entire home/apt,2.0,1.0,2.0,$40.00,NaN,NaN,1,1125,0,38.944420,-76.968086,Mount Rainier,20712,MD
19,NaN,NaN,3,2,Private room,1.0,1.0,1.0,$135.00,NaN,NaN,1,1125,0,38.983942,-77.019730,Takoma Park,20912,MD
20,100%,100%,1,2,Entire home/apt,1.0,1.0,1.0,$100.00,NaN,NaN,1,1125,0,38.945508,-76.970515,Mount Rainier,20712,MD
21,NaN,NaN,3,2,Private room,1.0,1.0,1.0,$225.00,NaN,NaN,1,1125,0,38.984198,-77.019996,Takoma Park,20912,MD
22,NaN,NaN,1,7,Entire home/apt,4.0,3.0,3.0,$129.00,$99.00,$99.00,14,1125,0,38.982899,-77.017649,Takoma Park,20912,MD
23,100%,100%,1,1,Entire home/apt,1.0,1.0,1.0,$149.00,NaN,NaN,3,31,46,38.928761,-77.048088,Washington,20008,DC
24,100%,100%,2,4,Entire home/apt,1.0,1.0,2.0,$150.00,$30.00,$100.00,2,365,84,38.909018,-77.033178,Washington,20005,DC
25,53%,69%,1,4,Entire home/apt,1.0,1.5,1.0,$175.00,$25.00,NaN,1,1125,25,38.906831,-77.029876,Washington,20005,DC
26,100%,100%,1,3,Entire home/apt,2.0,1.0,2.0,$239.00,$50.00,NaN,5,1125,4,38.912855,-77.022184,Washington,20001,DC
27,56%,83%,1,4,Private room,1.0,1.0,2.0,$65.00,NaN,NaN,2,1125,2,38.906025,-77.021406,Washington,20001,DC
28,52%,84%,1,2,Private room,1.0,1.0,1.0,$71.00,$12.00,NaN,2,14,83,38.908365,-77.022820,Washington,20001,DC
29,97%,100%,3,2,Entire home/apt,1.0,1.0,1.0,$80.00,NaN,NaN,1,1125,19,38.908232,-77.025092,Washington,20001,DC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3693,90%,0%,2,1,Private room,1.0,1.0,1.0,$100.00,NaN,$250.00,1,1125,0,38.883644,-76.998215,Washington,20003,DC
3694,100%,67%,1,6,Entire home/apt,2.0,2.5,4.0,$125.00,NaN,NaN,1,1125,3,38.891484,-76.984784,Washington,20002,DC
3695,100%,NaN,1,4,Entire home/apt,1.0,1.0,2.0,$145.00,$50.00,$100.00,3,60,0,38.880775,-76.985834,Washington,20003,DC
3696,100%,100%,2,2,Private room,1.0,1.0,1.0,$70.00,NaN,NaN,1,6,177,38.889593,-76.988789,Washington,20003,DC
3697,100%,100%,1,3,Entire home/apt,1.0,1.0,2.0,$75.00,$50.00,$100.00,2,1125,0,38.886758,-76.982555,Washington,20003,DC
3698,100%,100%,1,2,Entire home/apt,1.0,1.0,2.0,$180.00,$35.00,NaN,2,1125,102,38.890624,-76.995733,Washington,20003,DC
3699,30%,100%,2,4,Entire home/apt,3.0,1.5,2.0,$220.00,$150.00,$500.00,3,1125,7,38.885054,-77.002975,Washington,20003,DC
3700,99%,96%,32,4,Entire home/apt,2.0,1.0,3.0,$189.00,$75.00,$200.00,4,200,11,38.880481,-76.983665,Washington,20003,DC
3701,50%,NaN,1,2,Entire home/apt,1.0,1.0,1.0,$90.00,NaN,NaN,3,1125,0,38.890973,-76.992672,Washington,20002,DC
3702,100%,100%,1,4,Entire home/apt,2.0,1.5,2.0,$250.00,NaN,$300.00,1,1125,4,38.888747,-76.982742,Washington,20003,DC
3703,92%,94%,30,6,Entire home/apt,2.0,2.0,2.0,$365.00,$150.00,NaN,3,999,15,38.889752,-77.000151,Washington,20003,DC
3704,98%,52%,49,6,Entire home/apt,1.0,2.0,3.0,$275.00,NaN,NaN,3,90,7,38.888705,-76.998164,Washington,20003,DC
3705,100%,100%,2,5,Entire home/apt,1.0,1.0,2.0,$97.00,$55.00,NaN,1,1125,51,38.888764,-76.985002,Washington,20003,DC
3706,80%,100%,1,6,Entire home/apt,2.0,2.0,2.0,$159.00,$110.00,NaN,3,365,100,38.879947,-76.985445,Washington,20003,DC
3707,100%,100%,1,3,Entire home/apt,0.0,1.0,1.0,$135.00,$50.00,$250.00,2,1125,17,38.887971,-76.996194,Washington,20003,DC
3708,71%,100%,1,2,Entire home/apt,1.0,1.0,1.0,$99.00,$80.00,$250.00,10,700,14,38.888414,-76.997405,Washington,20002,DC
3709,75%,75%,5,2,Private room,1.0,1.0,1.0,$129.00,$20.00,$129.00,1,120,5,38.886721,-77.002692,Washington,20003,DC
3710,96%,100%,1,2,Entire home/apt,0.0,1.0,1.0,$120.00,NaN,NaN,1,1125,199,38.885432,-77.006818,Washington,20003,DC
3711,100%,99%,5,2,Private room,1.0,1.0,2.0,$70.00,$15.00,NaN,2,1125,115,38.884153,-76.989954,Washington,20003,DC
3712,NaN,NaN,1,4,Entire home/apt,1.0,1.0,2.0,$165.00,$30.00,NaN,1,1125,0,38.891573,-76.991430,Washington,20002,DC
3713,100%,50%,1,5,Entire home/apt,3.0,1.0,3.0,$125.00,$75.00,$100.00,3,3,8,38.882534,-76.984721,Washington,20003,DC
3714,90%,100%,1,3,Entire home/apt,1.0,1.0,1.0,$109.00,NaN,NaN,1,1125,8,38.885251,-76.983890,Washington,20003,DC
3715,100%,100%,1,1,Private room,1.0,1.0,1.0,$139.00,$75.00,$500.00,1,1125,3,38.884140,-76.992884,Washington,20003,DC
3716,67%,67%,1,5,Entire home/apt,1.0,1.0,1.0,$150.00,NaN,NaN,1,1125,1,38.891167,-77.001699,Washington,20002,DC
3717,100%,0%,1,7,Entire home/apt,3.0,2.0,3.0,$285.00,$120.00,$350.00,2,1125,8,38.889217,-76.989095,Washington,20003,DC
3718,100%,60%,1,4,Entire home/apt,1.0,1.0,2.0,$135.00,$45.00,$400.00,3,60,19,38.885492,-76.987765,Washington,20003,DC
3719,100%,50%,1,2,Private room,1.0,2.0,1.0,$79.00,NaN,NaN,3,365,36,38.889401,-76.986646,Washington,20003,DC
3720,100%,100%,2,6,Entire home/apt,2.0,1.0,3.0,$275.00,$100.00,$500.00,2,2147483647,12,38.889533,-77.001010,Washington,20003,DC
3721,88%,100%,1,2,Entire home/apt,1.0,1.0,1.0,$179.00,$25.00,NaN,2,21,48,38.890815,-77.002283,Washington,20002,DC
3722,70%,100%,1,3,Entire home/apt,0.0,1.0,1.0,$110.00,$40.00,$200.00,2,1125,1,38.883646,-76.999810,Washington,20003,DC

In [3]:
file["bedrooms"].value_counts()

1.0     2533
2.0      511
0.0      392
3.0      190
4.0       44
5.0       21
6.0        8
8.0        2
10.0       1
Name: bedrooms, dtype: int64

### Uni-Variant model. only one parameter considered i.e. bedrooms

In [4]:
accom = 3 #we have a house containing 3 bedrooms
file["distance"] = np.abs(file["bedrooms"] - accom) #finding distance b/w all bedrooms and accom

In [5]:
file["distance"].value_counts()

2.0    2554
1.0     555
3.0     400
0.0     190
5.0       2
7.0       1
Name: distance, dtype: int64

In [6]:
k = 5 #we will be comparing 5 examples closest to our instance

### We are shuffling the data so that there's no biasedness

In [7]:
np.random.seed(1) #seed fixes the random variables. every seed has different set of values.
shuffle = np.random.permutation(file.shape[0])
shuffle #generated a random order of the indexes

array([ 574, 1593, 3091, ..., 1096,  235, 1061])

In [8]:
#we will now set our index equal to shuffle array 
file = file.set_index(shuffle)
file.head()

,host_response_rate,host_acceptance_rate,host_listings_count,accommodates,room_type,bedrooms,bathrooms,beds,price,cleaning_fee,security_deposit,minimum_nights,maximum_nights,number_of_reviews,latitude,longitude,city,zipcode,state,distance
574,92%,91%,26,4,Entire home/apt,1.0,1.0,2.0,$160.00,$115.00,$100.00,1,1125,0,38.890046,-77.002808,Washington,20003,DC,2.0
1593,90%,100%,1,6,Entire home/apt,3.0,3.0,3.0,$350.00,$100.00,NaN,2,30,65,38.880413,-76.990485,Washington,20003,DC,0.0
3091,90%,100%,2,1,Private room,1.0,2.0,1.0,$50.00,NaN,NaN,2,1125,1,38.955291,-76.986006,Hyattsville,20782,MD,2.0
420,100%,NaN,1,2,Private room,1.0,1.0,1.0,$95.00,NaN,NaN,1,1125,0,38.872134,-77.019639,Washington,20024,DC,2.0
808,92%,67%,1,4,Entire home/apt,1.0,1.0,1.0,$50.00,$15.00,$450.00,7,1125,0,38.996382,-77.041541,Silver Spring,20910,MD,2.0

In [9]:
file = file.sort_values("distance")
file.head()

,host_response_rate,host_acceptance_rate,host_listings_count,accommodates,room_type,bedrooms,bathrooms,beds,price,cleaning_fee,security_deposit,minimum_nights,maximum_nights,number_of_reviews,latitude,longitude,city,zipcode,state,distance
2266,NaN,NaN,1,7,Entire home/apt,3.0,2.0,3.0,$750.00,NaN,NaN,2,2,0,38.926916,-77.036654,Washington,20009,DC,0.0
3227,100%,NaN,1,6,Entire home/apt,3.0,2.5,3.0,$695.00,$190.00,"$1,000.00",3,365,37,38.908472,-77.044985,Washington,20036,DC,0.0
1116,80%,82%,2,6,Entire home/apt,3.0,2.5,3.0,$249.00,NaN,NaN,3,1125,4,38.917077,-77.007037,Washington,20002,DC,0.0
3698,NaN,NaN,1,6,Entire home/apt,3.0,2.5,2.0,$500.00,$100.00,$500.00,2,10,7,38.891613,-76.991073,Washington,20002,DC,0.0
2770,NaN,NaN,1,6,Entire home/apt,3.0,NaN,NaN,"$2,000.00",NaN,"$1,000.00",4,4,0,38.891488,-76.989592,Washington,20002,DC,0.0

In [10]:
file["price"] = file["price"].str.replace("$","").str.replace(",","").astype(float)

In [11]:
file["price"]

2266     750.0
3227     695.0
1116     249.0
3698     500.0
2770    2000.0
1311     299.0
1101     146.0
832      500.0
1235     375.0
3285     375.0
3593     450.0
1149     300.0
2717     165.0
2187     350.0
2003     900.0
1250     249.0
2788     250.0
2478     150.0
1939     289.0
3466     250.0
1199     399.0
326      120.0
387      300.0
3566     200.0
1111     440.0
1525     525.0
3202     199.0
1356     345.0
2596     299.0
1319     120.0
         ...
3146     160.0
3080      95.0
3015      75.0
1734      85.0
376      110.0
3381      95.0
220     1250.0
1945    1200.0
1260    1250.0
1933     150.0
541      155.0
921      239.0
1073     219.0
1217     130.0
2769      99.0
2129      99.0
1144     110.0
2928     135.0
1965     120.0
3140     125.0
3619     135.0
2402     149.0
3355     109.0
718       85.0
1817      65.0
1109     325.0
1932     149.0
1682     125.0
3137     129.0
2267     150.0
Name: price, Length: 3723, dtype: float64

In [12]:
file["price"].head().mean()

838.8

In [13]:
def k_neighbour(data,bed,k):
    np.random.seed(1)
    shuffle = np.random.permutation(len(data))
    data["distance"] = np.abs(data["bedrooms"] - bed)
    data = data.set_index(shuffle)
    data = data.sort_values("distance")
    k_neighbour = data["price"].head(k).mean()
    return "The average price of {} bedroom apartments is ${}".format(bed,k_neighbour)

In [14]:
k_neighbour(file,3,5)

'The average price of 3 bedroom apartments is $498.0'

In [15]:
k_neighbour(file,4,5)

'The average price of 4 bedroom apartments is $305.8'

In [16]:
file = pd.read_csv("dc_airbnb.csv")

In [17]:
np.random.seed(3)
file = file.set_index(np.random.permutation(len(file)))
file.head()

,host_response_rate,host_acceptance_rate,host_listings_count,accommodates,room_type,bedrooms,bathrooms,beds,price,cleaning_fee,security_deposit,minimum_nights,maximum_nights,number_of_reviews,latitude,longitude,city,zipcode,state
1771,92%,91%,26,4,Entire home/apt,1.0,1.0,2.0,$160.00,$115.00,$100.00,1,1125,0,38.890046,-77.002808,Washington,20003,DC
2883,90%,100%,1,6,Entire home/apt,3.0,3.0,3.0,$350.00,$100.00,NaN,2,30,65,38.880413,-76.990485,Washington,20003,DC
318,90%,100%,2,1,Private room,1.0,2.0,1.0,$50.00,NaN,NaN,2,1125,1,38.955291,-76.986006,Hyattsville,20782,MD
285,100%,NaN,1,2,Private room,1.0,1.0,1.0,$95.00,NaN,NaN,1,1125,0,38.872134,-77.019639,Washington,20024,DC
1679,92%,67%,1,4,Entire home/apt,1.0,1.0,1.0,$50.00,$15.00,$450.00,7,1125,0,38.996382,-77.041541,Silver Spring,20910,MD

In [18]:
file["price"] = file["price"].str.replace("$","").str.replace(",","").astype(float)

### Model will be trained on train data. and validated by applying on test data

In [19]:
train_data = file.iloc[0:int(len(file)*.75)].copy() #slicing and taking 75% of the shuffled data as train data
train_data.shape[0]

2792

In [20]:
test_data = file.iloc[2792:].copy() #slicing and taking 25% of the shuffled data as test data
test_data.shape[0]

931

In [25]:
def k_neighbour(bed):
    td = train_data
    np.random.seed(1)
    shuffle = np.random.permutation(len(td))
    td["distance"] = np.abs(td["bedrooms"] - bed)
    td = td.set_index(shuffle)
    td = td.sort_values("distance")
    k_neighbour = td["price"].head().mean()
    return k_neighbour

In [26]:
k_neighbour(3)

318.8

In [36]:
test_data["predicted price"] = test_data["bedrooms"].apply(k_neighbour)

In [38]:
test_data[["predicted price","price"]]

      predicted price  price
2759             89.0  120.0
1827            277.6  140.0
3622            277.6  299.0
1883            107.0   85.0
1289            277.6  175.0
1581            277.6  165.0
89              107.0   54.0
3033            107.0   49.0
2864            107.0  129.0
1305            107.0  110.0
2100            107.0  150.0
2048             89.0  119.0
2177            107.0   55.0
2661            107.0  168.0
1029            107.0   55.0
1329            107.0   90.0
39               89.0  105.0
1012            107.0  109.0
943             107.0   85.0
665             107.0  120.0
2872            107.0  104.0
452              89.0   90.0
780             107.0   97.0
3704            107.0  130.0
1148            107.0  100.0
177             107.0   85.0
2184            107.0   89.0
336             277.6  129.0
1918            107.0   90.0
2166            107.0   67.0
...               ...    ...
2306            107.0  100.0
834             277.6  125.0
2710            107.0  145.0
1498            107.0   70.0
337             107.0   75.0
3610            107.0  180.0
3576            318.8  220.0
2446            277.6  189.0
1447            107.0   90.0
2653            277.6  250.0
1964            277.6  365.0
1684            107.0  275.0
2528            107.0   97.0
3494            277.6  159.0
1143             89.0  135.0
2965            107.0   99.0
1705            107.0  129.0
3065             89.0  120.0
2923            107.0   70.0
1738            107.0  165.0
2707            318.8  125.0
3069            107.0  109.0
789             107.0  139.0
2304            107.0  150.0
968             318.8  285.0
3000            107.0  135.0
1667            107.0   79.0
3321            277.6  275.0
1688            107.0  179.0
1898             89.0  110.0

[931 rows x 2 columns]

### This model does a poor job of predicting as there's a lot of difference. This is because a single variable (bedrooms) is considered only.

* mean absolute error
* mean square error
* root mean square error

#### to avoid negative values we have taken absolute values

In [41]:
mean_abs_error = np.abs(test_data["price"] - test_data["predicted price"]).mean()
mean_abs_error

54.799355531686295

#### to avoid negative values we have squared.

In [45]:
mean_square_error = ((test_data["price"] - test_data["predicted price"])**2).mean()
mean_square_error #unit is also squared so $^2

15804.38302900105

In [46]:
rmse = np.sqrt(mean_square_error)
rmse

125.71548444404552

In [50]:
def k_neighbour(bath):
    td = train_data
    np.random.seed(1)
    shuffle = np.random.permutation(len(td))
    td["distance"] = np.abs(td["bathrooms"] - bath)
    td = td.set_index(shuffle)
    td = td.sort_values("distance")
    k_neighbour = td["price"].head().mean()
    return k_neighbour

In [51]:
test_data["predicted price"] = test_data["bathrooms"].apply(k_neighbour)

In [53]:
test_data[["predicted price","price"]]

      predicted price  price
2759            138.8  120.0
1827            236.6  140.0
3622            138.8  299.0
1883            138.8   85.0
1289            236.6  175.0
1581            138.8  165.0
89              138.8   54.0
3033            138.8   49.0
2864            138.8  129.0
1305            138.8  110.0
2100            138.8  150.0
2048            138.8  119.0
2177            138.8   55.0
2661            138.8  168.0
1029            138.8   55.0
1329            138.8   90.0
39              138.8  105.0
1012            138.8  109.0
943             138.8   85.0
665             138.8  120.0
2872            138.8  104.0
452             138.8   90.0
780             138.8   97.0
3704            138.8  130.0
1148            219.4  100.0
177             138.8   85.0
2184            138.8   89.0
336             138.8  129.0
1918            138.8   90.0
2166             93.8   67.0
...               ...    ...
2306            138.8  100.0
834             219.4  125.0
2710            138.8  145.0
1498            138.8   70.0
337             138.8   75.0
3610            138.8  180.0
3576             93.8  220.0
2446            138.8  189.0
1447            138.8   90.0
2653             93.8  250.0
1964            236.6  365.0
1684            236.6  275.0
2528            138.8   97.0
3494            236.6  159.0
1143            138.8  135.0
2965            138.8   99.0
1705            138.8  129.0
3065            138.8  120.0
2923            138.8   70.0
1738            138.8  165.0
2707            138.8  125.0
3069            138.8  109.0
789             138.8  139.0
2304            138.8  150.0
968             236.6  285.0
3000            138.8  135.0
1667            236.6   79.0
3321            138.8  275.0
1688            138.8  179.0
1898            138.8  110.0

[931 rows x 2 columns]

In [54]:
from sklearn.neighbors import KNeighborsRegressor

In [59]:
feature = "bedrooms"
target = "price"
knn = KNeighborsRegressor(algorithm="brute",metric="euclidean")
knn.fit(train_data[feature],train_data[target])
prediction = knn.predict(test_data[feature])
prediction

ValueError: Expected 2D array, got 1D array instead:
array=[1. 3. 1. ... 1. 1. 1.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.